# Generated by Django 5.2.14 on 2026-05-16 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agile', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('task', 'Task'), ('subtask', 'SubTask'), ('comment', 'Comment'), ('sprint', 'Sprint'), ('epic', 'Epic'), ('project', 'Project')], max_length=16, verbose_name='entity type')),
                ('entity_id', models.PositiveIntegerField(verbose_name='entity id')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('commented', 'Commented')], max_length=32, verbose_name='action')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='old value')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='new value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'activity log',
                'verbose_name_plural': 'activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor'], name='activity_ac_actor_i_29e3da_idx'), models.Index(fields=['project', '-created_at'], name='activity_ac_project_eaf88d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_ac_entity__564be5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('edited', models.BooleanField(default=False, verbose_name='edited')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='activity.comment', verbose_name='parent comment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='agile.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='activity_co_task_id_fec19a_idx'), models.Index(fields=['author'], name='activity_co_author__ce4ab1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('assigned', 'Assigned'), ('commented', 'Commented'), ('mentioned', 'Mentioned'), ('status_changed', 'Status Changed'), ('due_soon', 'Due Soon')], max_length=32, verbose_name='verb')),
                ('entity_type', models.CharField(choices=[('task', 'Task'), ('subtask', 'SubTask'), ('comment', 'Comment'), ('project', 'Project'), ('sprint', 'Sprint')], max_length=16, verbose_name='entity type')),
                ('entity_id', models.PositiveIntegerField(verbose_name='entity id')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='activity_no_recipie_523283_idx'), models.Index(fields=['recipient', '-created_at'], name='activity_no_recipie_51e151_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_no_entity__34bd4b_idx')],
            },
        ),
    ]
